### ISSUE TITLE
Question: purpose of injectStatsEventsToSpan 

### ISSUE THREAD

**Issue by a631807682** [hertz-contrib/obs-opentelemetry#25]
**Describe the question**

I see we inject a lot of event into the span. I would like to know the purpose of these indicators and thus determine what I should do with them. Now when I look at the logs (either in jaeger or kibana) it's a little messy.

https://github.com/hertz-contrib/obs-opentelemetry/blob/main/tracing/tracer_server.go#L117

(We seem to be missing a question template)

**Comment by rogerogers** [comment]
These events label the time information of some important nodes in the request lifecycle, and they can be disabled through configuration if not needed.

```go
server.Default(tracer, server.WithTraceLevel(stats.LevelBase))
// or
server.Default(tracer, server.WithTraceLevel(stats.LevelDisabled))
```

**Comment by rogerogers** [comment]
Kitex has documentation [observability/instrumentation](https://www.cloudwego.io/docs/kitex/tutorials/observability/instrumentation/#stats-level), but it seems that Hertz is missing this part of the documentation.

cc @li-jin-gou

**Comment by a631807682** [comment]
Thanks for your reply, I have no further questions, if it's related to the documentation I'll keep it open, otherwise I'll close it.

**Comment by li-jin-gou** [comment]
open it



---Original---
From: ***@***.***&gt;
Date: Tue, Oct 17, 2023 22:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hertz-contrib/obs-opentelemetry] Question: purpose ofinjectStatsEventsToSpan  (Issue #25)




 
Thanks for your reply, I have no further questions, if it's related to the documentation I'll keep it open, otherwise I'll close it.
